### ISSUE TITLE
Can i get a drupal/graphql module which enables drupal/graphql_core module to work?

### ISSUE THREAD

**Issue by prrenish** [drupal-graphql/graphql#1113]
Hi I am new to this drupal module and I am trying my best to get all the working feature such as articles, blog and user interaction into the graphql interface and many of modules like drupal/graphql_twig and drupal/graphql_views are still using the drupal/graphql_core module and since you guys have removed it from the composer can you give me alternative for this cause all the output of graphql I am getting is the one which is provided by the composable_example.

![Screenshot from 2020-11-12 16-37-14](https://user-images.githubusercontent.com/45816962/98932522-73098500-2505-11eb-8a7e-bb6f13de7cad.png)
Adanced Thanks.

**Comment by simon-olsen** [comment]
Hi @prrenish. I ran into the same issue. The v4 of the module is pretty bare bones and requires you to put together the schema yourself (usually by copying the Composable Example module into your `modules/custom` and building upon that).

I can see why this is the case ([watch this video from Decoupled Days](https://www.youtube.com/watch?v=8qAXtDli5WE) to find out more) but I'm guessing you're probably like me and just want to see your Drupal nodes and all their fields available in the GraphiQL explorer without having to write an API/schema yourself.

I recommend installing v3 of the module - that comes with a nice, opinionated schema that will allow you to start querying your Drupal content. `composer require drupal/graphql:^3`

NOTE: If you've already installed v4, uninstall **both** the `graphql` module as well as the `typed_data` module. Otherwise you're going to get some nasty errors when you enable the v3 module.

In saying all this, it would be great to see an opinionated schema provided with the v4 module like it is in v3. I've also seen some talk of a UI to help build a schema via the Drupal admin backend which would be amazing! Once I get this decoupled project of mine done, I will hopefully have the bandwidth to help out. 🤞 

```
drush pm-uninstall graphql typed_data -y
composer remove drupal/typed_data drupal/graphql
```

Hope this helps 😃
