### ISSUE TITLE
Unknown named parameter $access_user

### ISSUE THREAD

**Issue by memic84** [drupal-graphql/graphql#1147]
Hi there,

We are having an issue, while connecting Drupal GraphQL to a decoupled frontend. The same errors occurs in the frontend as in the query explorer: `Unknown named parameter $access_user`

Our Drupal permissions seem to be alright.

Any ideas?

**Comment by arnovdw** [comment]
Hi,

If we check https://www.php.net/manual/en/migration80.incompatible.php  the following explanation comes up:
**"call_user_func_array() array keys will now be interpreted as parameter names, instead of being silently ignored."**

Inside /src/Plugin/GraphQL/DataProducer/DataProducerPluginBase.php we have the following code:
`
  return call_user_func_array(
    [$this, 'resolve'],
    array_merge($context, [$field])
  );
`

The key 'access_user' inside $context, does not comply with the key $accessUser inside the resolve function in \Plugin\GraphQL\DataProducer\Entity.

This gives the following error: **Unknown named parameter $access_user**

To fix this, we need to use the array values, as shown below:
`
    return call_user_func_array(
      [$this, 'resolve'],
      array_values(array_merge($context, [$field]))
    );
`

**Comment by klausi** [comment]
Interesting, so this is a PHP 8.0 issue? Maybe we can enable PHP 8 testing to see this fail? Will try that quickly.

**Comment by klausi** [comment]
Yep, definitely failing on PHP 8. I will merge your PR now and then check again how far we can get with PHP 8 coverage.
