### ISSUE TITLE
[Question] Public Permissions  

### ISSUE THREAD

**Issue by shawnmmatthews** [drupal-graphql/graphql#143]
I was able to build out a quick react/apollo/graphql app using Drupal 8. Thanks again for the great module. I do however have a question. How are you handling permissions regarding the public user version of the site? Is there a best practice for locking the data down to queries only (and preferably specific queries at that) when run from the client? Am I ok if I simply lock down GraphIQL to admin, and then limit my apps actions to just queries for the time being? Thanks again. I really appreciate any insight you can provide.

**Comment by fubhy** [comment]
You can lock down your schema in different ways.

First of all, obviously you can limit the data returned from the schema simply through permissions. We respect entity access permissions so if a user does not have access to "view" a given node, they won't be able to query it through nodeById() or nodeQuery(), etc. ...

Secondly, if you are using React / Apollo you can actually use a concept called "persisted queries" to completely lock down your schema to just allow the queries defined in your app's code base: https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5

We support this feature and there is actually a demo for this built into this example app I put together: https://github.com/fubhy/drupal-decoupled-app. Basically, the script statically analyzes your code base and extracts all gql queries into a .json file which you can import into your Drupal backend. With the latest 8.x-3.x-dev of drupal/graphql you simply need to enable the graphql_query_map_entity module which will allow you to import and store these query maps as config. The query map's file content is then hashed and the hash then makes up the "api version". The app can now still request data by sending the "api version" and "query id" rather than the full query string. 

The "query id" and "api version" are then used to look up the query string from your stored query map configs. See here: https://github.com/fubhy/graphql-drupal/blob/8.x-3.x/src/Routing/QueryRouteEnhancer.php#L159-L185

This also allows you to use GET queries instead of POST queries because the request payload is much smaller. The demo app I linked also supports that (and batch queries). Check it out in "production" mode to see that in action. This is the code where that happens: https://github.com/fubhy/drupal-decoupled-app/blob/master/frontend/app/shared/state/configureApolloClient.js#L121-L153.

I didn't add any permissions yet to distinguish between full query string requests and "persisted query" requests. Theoretically, however, it would now be possible to disallow access to the api with full queries and only allow persisted queries. This could be done through two separate permissions. I think I will add that later. I need that too.

The last option is also possible but trickier and doesn't necessarily fit your use-case. I can see it being useful in certain scenarios however: Theoretically it is also possible to set up multiple different schemas based on different contexts. We cache the generated schema with cache contexts, you could therefore actually add cache metadata for the vectors that you want it to care about. You would then get multiple different schemas based on e.g. the current user.

**Comment by fubhy** [comment]
Let me know if that helps. You can also send me your e-mail address if you have further questions about this. I can then invite you to our slack channel.

**Comment by shawnmmatthews** [comment]
Thanks so much @fubhy ! I really appreciate it!
