### ISSUE TITLE
How do we handle metatag/address/custom field?

### ISSUE THREAD

**Issue by chuongle** [drupal-graphql/graphql#144]
I know the module does not support yet but if there is any instruction on how to handle these, that would be awesome! It would be great to learn how to build these for Drupal!

**Comment by fubhy** [comment]
You can build plugins for specific field types. See the implementation for the entity reference or link fields.

**Comment by pmelab** [comment]
`graphql_content` creates a *rendered* field for every field in your display configuration, which will just spit out the rendered string as a default behaviour. To override this, you just have to create a new field plugin with the same name that binds to the same type. E.g. a `body` field for `NodeArticle`. Then you can do whatever you want.

Most extension modules override fields based on the configured field formatter, using the `FieldFormatterDeriver`. Have. look at the [LinkField](https://github.com/fubhy/graphql-drupal/blob/8.x-3.x/modules/graphql_link/src/Plugin/GraphQL/Fields/LinkField.php)'s annotation. The address extension would be very similar (and a great contribution! 😄).


About metatags:
I suppose you are talking about the [metatag](http://www.drupal.org/project/metatag) module? I recently did a hacked integration for one of our projects, with a different approach though. I bound the field to the `Url` type, so we can fetch metatags by path, since the ones stored directly into nodes are just half of the story:

```
query {
   route(path:"/node/1") {
    metatags {
      key
      value
    }
  }
}
```

#145 is not a solution I would commit right now, but could be a starting point.

**Comment by chuongle** [comment]
@pmelab That's awesome! Thanks for starting this!

I'm pretty new to this so can you explain a little more about your first point? What do you mean by `create a new field plugin with the same name that binds to the same type`? Is this the graphql field types or is this the field_formatter type for the display? Does the render display format of the field  affect the return value of the field in graphql?

**Comment by pmelab** [comment]
I don't know how familiar you are with [Drupal's Plugins and Plugin Derivers](https://www.drupal.org/docs/8/api/plugin-api/plugin-api-overview). This is crucial to understand whats going on.

> Is this the graphql field types or is this the field_formatter type for the display?

I'm talking about the GraphQL field type. Without thinking about any Drupal content types, or formatters, the `graphql_core` module assembles the GraphQL schema from *type*, *field*, *interface* and a couple of other plugin types. To add anything to your schema, you just have to implement the respective Drupal Plugin. Have a look at the annotation of the [Wheels field](https://github.com/fubhy/graphql-drupal/blob/8.x-3.x/modules/graphql_core/tests/modules/graphql_plugin_test/src/Plugin/GraphQL/Fields/Wheels.php) from the tests in `graphql_core`.

```
/**
 * The number of wheels a vehicle has.
 *
 * @GraphQLField(
 *   id = "wheels",
 *   name = "wheels",
 *   type = "Int",
 *   types = {"Vehicle"}
 * )
 */
...
```

This defines a field named *"wheels"*, that returns an integer value and will appear on the *"Vehicle"* type. Thats how you manually add something to the schema.

*On top of that* `graphql_content` automatically generates these plugins for content entities and the fields defined in their `graphql` view mode. But the fields just output the rendered string.

> Does the render display format of the field affect the return value of the field in graphql?

*And on top of **that***, extension modules like `graphql_link` look for fields that are configured with a specific *field formatter* and override the *"just the rendered string"* behaviour. And yes, thats where the formatter (indirectly) affects the fields return type.

**Comment by chuongle** [comment]
@pmelab Thanks for your explanation. I used Drupal Plugin before to build Custom Block Plugin. Everything is getting a little clear for me. Still need to do some more research to make sure I understand more. 

In the mean time, I made a PR #147 to support address field. Please review and let me know what to fix. This is a learning opportunity for me.

Thanks!

**Comment by pmelab** [comment]
Hey! Technically your implementation is correct, but as @fubhy stated in #147, what you are doing is a hard-coded version of #133. I'm very sorry I did not think of that earlier. I hope it still was an opportunity to learn 😓 

Feel free to join in on #133, this will be quite interesting.

**Comment by fubhy** [comment]
I actually just had a short meeting with @blazeyo about #133 . He is going to continue working on this after I gave him some hints for the implementation. If you want to join our Slack that would probably be the best way to meet @blazeyo and maybe talk about how / if you can lend him a hand in any way (in case you are interested!).

**Comment by chuongle** [comment]
@pmelab @fubhy No worries. At least I understand how the module works. Please add me into Slack using my email chuongtdle91@gmail.com. Thanks for all your help!
