### ISSUE TITLE
 The "" entity type does not exist

### ISSUE THREAD

**Issue by anakinjay** [drupal-graphql/graphql#16]
`Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 125 of /docroot/core/lib/Drupal/Core/Entity/EntityTypeManager.php).`

I have several custom entity types created by drupal console. My gut tells me the issue is with those custom types somewhere but I haven't been able to figure out where.

**Comment by fgm** [comment]
Are you still having this problem ? There were no comments in 3 months on this issue, so I'm going to assume it was fixed unless you tell us otherwise. If you're still having the problem, some debugging steps:

* can you use the module on a fresh install without these custom entities ?
* can you use your custom entities normally elsewhere ?

**Comment by ctrladel** [comment]
Recently ran into this. Turns out I had a media entity view with `targetEntityType: null` in my config. This caused `graphql/modules/graphql_core/src/Plugin/Deriver/Enums/DisplayModeIdDeriver.php:73` to try and load the definition of `null.media_library`. Updating the config to the correct entity corrected the issue for me.
