### ISSUE TITLE
[REQUEST] support "operationName"

### ISSUE THREAD

**Issue by ClemensSahs** [drupal-graphql/graphql#176]
```gql
query query1 {
  nodeQuery {
  }
}

query query2 {
  entryGraphql1View {
  }
}
```

**expected behavior**
```operationName=query2``` only run the 2nd query

**current behavior**
all operation running

**Comment by fubhy** [comment]
Why would that be the expected behavior? If you send two queries, both of them should be executed. If you only want one to be executed, just send one!

The operation name is used to:

a) distinguish two queries / mutations if you got multiple in the same payload. 
b) to identify querries in your backend for debugging/logging purposes.

That's about it (except for some special use cases e.g. when statically analyzing your queries in your client's code base to e.g. produce a persisted query map).
