### ISSUE TITLE
FIeld plugin cacheability metadata should only be added to a response on demand

### ISSUE THREAD

**Issue by xuxucode** [drupal-graphql/graphql#323]
Currently the field plugin cacheability metadata is added to the GraphQL schema, then eventually to every GraphQL response, even that field is not used in a GraphQL query.

For example, a cacheable node title field and an uncacheable user name field:

```php
/**
 * A cacheable node title field.
 *
 * @GraphQLField(
 *   id = "node_title",
 *   name = "title",
 *   type = "String",
 *   types = {"Node"},
 * )
 */
class NodeTitle extends FieldPluginBase {}

/**
 * An uncacheable user name field.
 *
 * @GraphQLField(
 *   id = "user_name",
 *   name = "name",
 *   type = "String",
 *   types = {"User"},
 * )
 */
class UserName extends FieldPluginBase {

  // Uncacheable.
  public function getCacheMaxAge() {
    return 0;
  }
}

```
This will lead to the GraphQL cache useless to every whatever query, because the respose is uncacheable.

For example,  we don't query the user name field, but it's uncachable:

```graphql
nodeQuery(id="1") {
  title
}
```

Another example, `MutationPluginBase` also makes the cache useless:

```php
namespace Drupal\graphql_core\GraphQL

abstract class MutationPluginBase {
  
  /**
   * {@inheritdoc}
   *
   * Disable cache because mutations should never cache.
   */
  public function getCacheMaxAge() {
    return 0;
  }

}
```

Only adding the field plugin cacheability to a response on demand makes more sense, any thoughts on this?

**Comment by fubhy** [comment]
You are conflating schema and response data cache metadata. The cache metadata on the field plugin itself is used for caching the schema. So getCacheMaxAge, getCacheTags, etc. those are all not directly used for cache metadata of the response when the field is queried but for caching the field plugin in the schema. The response data cache metadata however also contains the schema cache metadata. Why? Because each response is bound to a particular schema. So when we return the cache metadata for a response of a query, we merge it with the cache metadata of the schema that was used before returning it. This is required because obviously when invalidating a schema the result also potentially changes.

Considering this, the code in https://github.com/fubhy/graphql-drupal/blob/8.x-3.x/modules/graphql_core/src/GraphQL/MutationPluginBase.php#L69 (MutationPluginBase as mentioned by you) seems wrong. Because this causes every schema that contains a mutation to not be cachable at all. I'll check this together with Philipp on Monday.

**Comment by xuxucode** [comment]
Thanks, that  makes sense.

**Comment by fubhy** [comment]
@pmelab what's your opinion about this? (MutationPluginBase)

**Comment by fubhy** [comment]
Yep, this is clearly not right (just tested it). I submitted a PR that should fix it.
