### ISSUE TITLE
Move plugin system to graphql module root

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#355]
The GraphQL module doesn't do anything in regard to the actual data crud. The graphql_core is the module that defines the plugins. But it also provides various plugin instances like context or entity queries. I think this should be moved into the graphql_content module since it makes it impossible not to expose those "fields" in the root schema. And re-defining all plugins that graphql_core defines only to avoid exposure of these "fields" is bad DX.

**Comment by pmelab** [comment]
Thats the first time somebody wants more configurability 😄 

During Drupalcon we actually got the feedback to consolidate, simplify and expose even more by default. And `graphql_content` would perhaps disappear at some point. The "hiding" part should be left to Drupal's access system.

Could you explain your use case in more detail so we get an idea of the problem space?

/cc @wimleers @fubhy

**Comment by fubhy** [comment]
I disagree with both of you partly and agree with both of you partly too.

My suggestion: Move the plugin system to /graphql (root module) and leave the plugin definitions in place (graphql_core).

**Comment by pmelab** [comment]
> I disagree with both of you partly and agree with both of you partly too.

You would be a very good politician.

**Comment by ghost** [comment]
@pmelab my use case is that i have a massive ecommerce distribution that I am going to rewrite into headless design and I will build the API on GraphQL but I have to have 100% control over it. That means access, naming, ... and right now the API is completely exposed. Not to mention that current design is simply wrong. ...what fubhy suggests is totally ok with me.

I am unsure about the future of the graphql_core but graphql should contain only the basics that devs can build upon without any obstacles in place. Something like Page Manager + Page Manager UI....one does not have to use both.

**Comment by fubhy** [comment]
I suggest you adapt your wording slightly. You have no clue how the module came to the place it is in right now. The plugin system was added on top of the core "graphql" module as a submodule so that you can even use graphql without any plugins at all (just by providing your own completely custom schema). It then grew over time. The design is not wrong just because it doesn't fit your use-case perfectly without any work from your side. What you are trying to do works by simply using alter hooks anyways or not using the plugin system at all. Something is not wrong because you disagree with it.

**Comment by fubhy** [comment]
That said, moving the plugin system to "graphql" has been discussed by @pmelab and me before and we are likely to do it. The configuration interfaces and any concrete plugin implementations are then optional additions. So that would solve your "problem" (you don't actually have a problem atm as I mentioned before).

**Comment by ghost** [comment]
I am not saying the code is wrong. I'm saying that putting plugin annotations and interfaces along with definitions(instances) into the same code base is a bad design, which seems we agree upon. That's all.

**Comment by pmelab** [comment]
And we are not saying that you are not right. We are saying that putting the words "simply wrong" along with a request for support into the same text is bad behaviour. That's all.

**Comment by fubhy** [comment]
That's the whole point. A little nicety comes a long way when formulating support requests / suggestions. Something is not wrong because you disagree. And something is not bad design because it doens't work perfectly in your use-case. It's designed in a certain way because of reasons that you don't know and might have grown organically that way.

**Comment by fubhy** [comment]
Anyways, back on topic... We are going to move the plugin system to the /graphql root module as suggested by me earlier.

**Comment by fubhy** [comment]
Done.
