### ISSUE TITLE
Timezone not exposed as part of user fields / properties

### ISSUE THREAD

**Issue by fjgarlin** [drupal-graphql/graphql#368]
Timezone information is currently not exposed when querying the User entity. 

**Suggested solution**
Add a plugin for that. It's probably a property on the user object and not a field. 
Create a generic plugin for entity properties based on typed data.

**Comment by fubhy** [comment]
We would want a generic plugin for that instead (expose all entity properties). Since we currently only have control of fields via the field display options, however, that would need further considerations and work than just exposing all properties blindly. Probably something that we would need a full configuration interface for.
