### ISSUE TITLE
Where's the 8.x-2.x branch?

### ISSUE THREAD

**Issue by stmh** [drupal-graphql/graphql#37]
Hi, I am preparing some minor fixes for the 8.x-2.x branch but can't find it on GitHub. What's the official way to go? File issues on Drupal.org and provide patches, or can we issue pull requests  here on GitHub?

Here are my two fixes and 1 code style:
* https://github.com/factorial-io/graphql-drupal/commit/056a6c025b2146fffaf6a1944a2bc02968fc77e9
* https://github.com/factorial-io/graphql-drupal/commit/188d1eac749bfd3f26984a489cc89f9935a531d7
* https://github.com/factorial-io/graphql-drupal/commit/c276ae2f13d4ea9a6363b5b77c433f6e153119b3

thanks,
stephan

**Comment by fubhy** [comment]
Hi. I am no longer maintaining the 2.x branch because we decided to head down a fundamentally different path for schema generation. The 3.x branch's goal now is to build a sophisticated and pleasant API for crafting custom schemas through code. Once we consider it stable enough we will merge in a submodule that automatically exposes the Drupal data graph as a schema. This is already under heavy development and nearly ready.
