### ISSUE TITLE
Document plugin caching

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#384]
It looks like all plugin base classes use the `\Drupal\graphql\Plugin\GraphQL\Traits\CacheablePluginTrait`, yet there is no mention about this in plugin annotations.

I think the treat should be made into abstract class + interface and added "properly" to all plugin base classes and documented in plugin annotations.

**Comment by fubhy** [comment]
We use traits for embedding the Youshido type classes into plugins because we need to extend the abstract classes from the library since the library fails to provide interfaces and checks on the abstract class inheritance in many critical places in the code. Hence this is not possible.

We can of course add interfaces on our side for this and require that they are implemented and check for them in the plugin manager.

**Comment by fubhy** [comment]
We actually have these documented in the type system plugin interface.
