### ISSUE TITLE
Mutations of referenced entities through entity reference field

### ISSUE THREAD

**Issue by sebas5384** [drupal-graphql/graphql#405]
(first of all, thanks for this awesome module, really game changing for Drupal)

Hi! I'm using the `profile` module in order to create a user with a profile, and I would like to do it at the same mutation query, so in that way validations could rollback the creation of a user because the profile has some invalid field, like a required field for example.

There's something already being done for that, or should be created a new module like `graphql_entity_reference_mutation` ?

cheers!

**Comment by fubhy** [comment]
Our generated mutations are currently very basic and frankly, generating mutations based on entity fields / properties is not very efficient because the schema becomes quite messy. To be honest, I think it's best to create specific, custom and very focused mutations manually by writing custom mutation plugins. It's very simple to do that with the plugin system for mutations. I am actually wondering if we should remove the generated mutations altogether because they are not very useful anyways and instead wait for Rules or so to do a stable release and then generate mutations based on Rules configuration instead.
