### ISSUE TITLE
Subscription support

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#424]
Is there a support for subscriptions? I'm interested in implementing a SSE.

**Comment by fubhy** [comment]
No. Because we are in PHP, it's traditionally not possible to support websockets. Not yet at least. There are things like ReactPHP (https://reactphp.org/) which you could build an implementation around but neither Youshido's nor Webonyx's library for GraphQL in PHP support that. And so we don't support it either. Nothing would stop you from adding a Node based GrapHQL server on top (with Subscriptions) that would get pinged by your Drupal  backend on changes and re-fetch queries or so. But obviously that's not ideal. So the answer for now is: No.

**Comment by fotiDim** [comment]
@fubhy Is this still the case? What is the recommended route now for a project that needs subscriptions?

**Comment by Kingdutch** [comment]
@fotiDim You're reviving quite an old issue so a new one may have been better. However for anyone else that comes across this. webonyx/graphql-php supports the subscription operation and there's nothing inherently in the resolvers that make it not work.

The biggest issue in a Drupal context is that Drupal doesn't support persistent connections. So you'll have to set up a separate system to handle that. You could use ReactPHP for that as I outlined in my [lightning talk at GraphQL Galaxy](https://www.youtube.com/watch?v=A8MhCef27CE).

**Comment by fotiDim** [comment]
@Kingdutch thanks for the link to your video. Even through I understand the missing  parts for having subscriptions working ,I cannot estimate how much effort it would be to replicate your setup. Is it already part of OpenSocial?

Can't we just reopen this issue now that there is light at the end of the tunnel?

**Comment by Kingdutch** [comment]
It's not part of what we have open sourced at Open Social. In terms of amount of work I think we spent about 6-12 months on it.

We shouldn't re-open this issue because from a GraphQL module's point of view there's no work to be done. All the work done which I presented in the lightning talk was done outside of the GraphQL module (and mostly outside of Drupal).
