### ISSUE TITLE
Route Query doesn't translate entity references

### ISSUE THREAD

**Issue by pavlosdan** [drupal-graphql/graphql#463]
Calling a route query as a default language brings in all the correct fields with their values in the default language(in this case english).
![language-default](https://user-images.githubusercontent.com/5995324/34657833-263e9978-f465-11e7-8c8b-00fa5df18d15.png)

Adding chinese to the path it was expected that we would get the translated node with all the references translated as well. What we get instead is the translated node with its fields in chinese (title, description) but the references (widgets) in english.
![language-chinese](https://user-images.githubusercontent.com/5995324/34657876-7a0a0786-f465-11e7-9d3a-882f1add9a44.png)

So far the only way we found to get the translated references was to wrap all references in "entityTranslation" and pass in the language through a variable. e.g:
![language-chinese-wrappedentitytranslation](https://user-images.githubusercontent.com/5995324/34657902-a4a4e4d4-f465-11e7-8faf-8dfe18940362.png)

Shouldn't the route query return the translated entities as well without the need to wrap them into entityTranslation?

**Comment by fubhy** [comment]
This is tricky because we cannot just set the global language based on the path of what was passed to the route() root field. Why? Because then other queries outside of the route() root field would be affected too. Not good. We do not currently have a way to set a contextual value for a specific set of sub-selections (e.g. only set the language for everything below the route() root field). This is simply something that the spec doesn't mention and the php graphql library that we use doesn't support. We could explore how to add such a feature. I would even have a vague idea how to design an API for that. But it would definitely require some work on the library implementation itself.

We should maybe override the generic entity field deriver for entity reference fields and add a language parameter so you could at least fetch related entities without having to go through the extra entityTranslation step. That would be an easy quick win but would require your queries to pass the language parameter to each of those fields. Not ideal.

I think the way to go would be to enhance the ResolveInfo object with field-level contexts that are inherited and copied from their parents (and can be overridden as the tree is being traversed). We would probably end up with a similar API as contexts (think "refining contexts") as Rules does.

 /cc @pmelab

**Comment by fubhy** [comment]
Will be solved with #509
