### ISSUE TITLE
Voyager page not working

### ISSUE THREAD

**Issue by johnreytanquinco** [drupal-graphql/graphql#540]
Graphql: 8.x-3.0-beta5
After installing and enabling the module, the voyager page is not displaying properly
`bash-4.2$ composer require drupal/graphql`

`abort(7) at Error at Ga (blob:http://localhost:8080/e5cbdb6b-5f4a-4aa7-856f-c6e1954492bb:420:124) at Fa (blob:http://localhost:8080/e5cbdb6b-5f4a-4aa7-856f-c6e1954492bb:420:22) at v (blob:http://localhost:8080/e5cbdb6b-5f4a-4aa7-856f-c6e1954492bb:1554:101) at Array.hR (blob:http://localhost:8080/e5cbdb6b-5f4a-4aa7-856f-c6e1954492bb:1539:32781) at fv (blob:http://localhost:8080/e5cbdb6b-5f4a-4aa7-856f-c6e1954492bb:1533:28979) at $v (blob:http://localhost:8080/e5cbdb6b-5f4a-4aa7-856f-c6e1954492bb:1533:57063) at aw (blob:http://localhost:8080/e5cbdb6b-5f4a-4aa7-856f-c6e1954492bb:1533:61059) at bw (blob:http://localhost:8080/e5cbdb6b-5f4a-4aa7-856f-c6e1954492bb:1533:61151) at Xt (blob:http://localhost:8080/e5cbdb6b-5f4a-4aa7-856f-c6e1954492bb:1533:11673) at jc (blob:http://localhost:8080/e5cbdb6b-5f4a-4aa7-856f-c6e1954492bb:1528:753) If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.`

![screenshot from 2018-03-05 18-09-11](https://user-images.githubusercontent.com/7284893/36969411-5e38b126-20a0-11e8-83a1-9b083a9a8f58.png)

**Comment by fubhy** [comment]
What modules are you using besides graphql? I need the full set of modules to be able to properly debug this (because the generated schema is based on the modules that you are running in your setup).

Generally, the voyager page is working fine, so it is some sort of incompatibility with one of the other modules you are running and we have to figure out which one it is.
