### ISSUE TITLE
Cache metadata leaking out of non-cacheable processes

### ISSUE THREAD

**Issue by akshitggrwl** [drupal-graphql/graphql#610]
I have created a mutation for webform submission which triggers an email. The submission is created successfully but the response is not returned.
The following exception is thrown
`LogicException: The controller result claims to be providing relevant cache metadata, but leaked metadata was detected. Please ensure you are not rendering content too early. Returned object class: Drupal\Core\Cache\CacheableJsonResponse. in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()`

This was the issue with REST module also. [REST module must cache only responses to GET requests](https://www.drupal.org/project/drupal/issues/2626298)
The email is built in separate render context and it uses tokens from the webform which is same as rendering. Thus the Logic Exception.

In the RequestController for graphql, if i send Simple JsonResponse instead of CacheableJsonResponse, no exception is thrown.

**Comment by fubhy** [comment]
This is a different issue than the one you linked. We never cache mutations. The error you are seeing stems from cache contexts which are evaluated before the actual caching happens and it used to be a safety net for detecting leaky operations.

We've since removed this check. Your issue should therefore not exist if you upgrade to the latest beta.

**Comment by akshitggrwl** [comment]
I have updated to latest beta-8. But i still have this issue. 
I finally used the patch provided here https://www.drupal.org/project/drupal/issues/2663638 to solve this.

**Comment by rawxx** [comment]
Hi, thank you for pointing this Drupal Core patch, which actually seems to be the only solution to fix this error on my application so far. Unforunately, this patch fails some tests, and I won't take the risk to use it on a multiple site Drupal instance.

Isn't there anyway to chose weather or not to send cacheable Response from graphql module itself (not sure about what it means but using "simple JsonResponse instead of CacheableJsonResponse" like @akshitggrwl suggested ?

I have this exception using beta-8 or rc2, but not beta-5.

**Comment by rawxx** [comment]
Hi @fubhy , really sorry to tag you, would you have any hint about how to use JsonResponse instead of CacheableJsonResponse ?

**Comment by Leksat** [comment]
I'll describe my case. Maybe it will be helpful for someone.

In custom code I had a mutation that was doing nothing special - it was updating a drupal user account with some data. When this mutation was called with a POST /graphql request, I got
```
LogicException: The controller result claims to be providing relevant cache metadata, but leaked metadata was detected...
```

Then I googled this issue, and tried the patch from https://www.drupal.org/project/drupal/issues/2663638 mentioned by @akshitggrwl. The patch worked well. The initial error was gone, yet new errors came in. For example, I got the following when tried to update the order of terms on a taxonomy vocabulary page:
```
LogicException: Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call...
```

The error was happening because `OverviewTerms::buildForm` [renders some data](https://github.com/drupal/drupal/blob/646584b3f718897179589f4f014531e3d9365331/core/modules/taxonomy/src/Form/OverviewTerms.php#L275). This happens on POST requests as well, but #2663638 patch disables `wrapControllerExecutionInRenderContext` for POST requests.

So I removed the patch and started to investigate the original issue.

**To debug the leaked metadata error:** set a breakpoint in `Renderer::doRender` on [this line](https://github.com/drupal/drupal/blob/646584b3f718897179589f4f014531e3d9365331/core/lib/Drupal/Core/Render/Renderer.php#L243). Then execute the mutation (or whatever action that triggered the error).

The result of the debug for me was:
- `UpdateEntityBase::resolve` calls `$entity->validate()` 
- user account entity has an entity reference field
- the ER field uses views as the selection handler (which is used for the field validation)
- `ViewsSelection::validateReferenceableEntities` executes the selection handler view
- this triggers rendering

Here is the call chain:
<img width="883" alt="rendering-in-entity-validation" src="https://user-images.githubusercontent.com/989015/48899126-b7ef0980-ee5f-11e8-847a-800ebad86ea2.png">

To avoid the the leaked metadata error, I overrode `UpdateEntityBase::resolve` in my custom mutation:
- copied the original code
- removed `$entity->validate()` call

(I my case removing the validation was totally fine.)

**Comment by Leksat** [comment]
After a chat with @pmelab the solution was updated to:
```
  // on a class extending UpdateEntityBase
  public function resolve($value, array $args, ResolveContext $context, ResolveInfo $info) {
    return \Drupal::service('renderer')
      ->executeInRenderContext(new RenderContext(), function () use ($value, $args, $context, $info) {
        return parent::resolve($value, $args, $context, $info);
      });
  }
```

I'll created a PR for `UpdateEntityBase::resolve`.

**Comment by pmelab** [comment]
@fubhy Reopening and renaming this issue.
I discovered together with @Leksat that there are cases where setting an entity property emits cache metadata in the current render context. In our case a validation check of a field with a views entity selection that under the hood renders the view.

This means we have to wrap all non-cacheable executions (mutations ...) in their own render context or modify the controller to return a non-cacheable response in this case?

**Comment by Leksat** [comment]
Here is PR which wraps for all base entity update mutations with the render context: https://github.com/drupal-graphql/graphql/pull/701
Tested: it solves my issue with views entity selection.

**Comment by fubhy** [comment]
Okay, makes sense for mutations in this case! Merged.
