### ISSUE TITLE
Internal server error, when use query route(path: String!):

### ISSUE THREAD

**Issue by WillAcon** [drupal-graphql/graphql#641]
I'm having a problem with the latest version of graphql when executing the router query.
This is the following message:
`{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "route"
      ]
    }
  ],
  "data": {
    "route": null
  }
}`

it worked in an earlier version.

`{
  route(path: "/node/1") {
   ... on EntityCanonicalUrl {
      entity {
        ... on NodeRecipe { 
              title
              nid
        }
      }
    }
  }
}`

**Comment by fubhy** [comment]
Hey @WillAcon. Sorry for the late reply. We've all been pretty busy.

Does this problem still persist? If yes, could you enable the "development" mode through the service parameter (check graphql.services.yaml). Once that's enabled, you will get a more detailed error message. Without that, I am afraid I won't be able to help because this is currently just a generic error message.

Please re-open this issue if the problem still persists. Make sure you try it with the latest 3.x-dev version :-). Thanks, and again sorry for the late reply.
