### ISSUE TITLE
Support for computed and bundle fields

### ISSUE THREAD

**Issue by duartegarin** [drupal-graphql/graphql#643]
Hi,
As discussed on Slack GraphQL currently isn't working for computed fields.
As an example you can see the company link field in this article:
https://www.drupal.org/node/2112677
As we discussed the issue might be that they don't have storage and so aren't discovered by GraphQL derivers.
Thanks!

**Comment by pmelab** [comment]
The derived schema only relies on field storage configuration and completely misses computed and bundle field definitions. This also has an effect on entity queues (#612). The derivers need to be adapted to get bundle specific typed data field definitions.

**Comment by duartegarin** [comment]
That makes sense.
I am using a custom field as a workaround for now.
Thanks 👍

**Comment by rafatwork** [comment]
I see this has been added to milestone v4. Has any work already been done for this? A project of mine needs computed fields to be retrieved via GraphQL - pretty soon actually.

I'm willing to put time into this, some more information on how/where to tackle this would be always be welcome of course.

**Comment by fubhy** [comment]
The issue is that we are currently using field storage definitions to derive the entity fields. I don't remember anymore why we did this. Here is the relevant code: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/Deriver/EntityFieldDeriverBase.php#L103-L117

It's used in derivers like this one for instance: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/Deriver/Fields/EntityFieldDeriver.php

**Comment by wimleers** [comment]
> The issue is that we are currently using field storage definitions to derive the entity fields. I don't remember anymore why we did this.

Related to this: https://github.com/drupal-graphql/graphql/pull/571#issuecomment-425033077

**Comment by fubhy** [comment]
https://github.com/drupal-graphql/graphql/pull/684/files
