### ISSUE TITLE
Custom Server Schema 

### ISSUE THREAD

**Issue by dalau6** [drupal-graphql/graphql#677]
In the beta version of GraphQL the default schema exposes all the Drupal fields. I'm trying to avoid exposing my entire schema to the client. What's the best way to define my own schema without changing anything from the module?

**Comment by fubhy** [comment]
You've got a few options for that. Firstly, you could use the hooks (e.g. as seen here: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/graphql.module#L57-L143) to alter the resulting schema. Then, you could always override the plugin definitions and plug in your own derivers to limit what they derive. Lastly, you can create your own, completely custom schema by providing your own schema plugin.

All that being said, this is going to be much easier in the next version (8.x-4.x) where we use SDL (Schema Definition Language) schemas as the default, assuming complete customization as the default. You can already use custom SDL schemas by coming up with your own sub-module that provides a schema plugin like seen in this proof-of-concept: https://github.com/drupal-graphql/graphql-sdl/blob/master/src/Plugin/GraphQL/Schemas/SdlSchemaTest.php

**One last, but importent remark**: While your concerns about schema "complexity" are valid (!), graphql always assumes that your schema is safe to be exposed publicly. There are no access restrictions on schema introspection by design. The fields themselves, when queried, are access protected. So, if your goal is to provide a "simpler" schema for your clients, then you should consider creating a completely custom schema. However, if your only concern is that it's not "safe" to expose the full schema: Don't worry about that.
