### ISSUE TITLE
Mixed Content Issue on fully decoupled Site

### ISSUE THREAD

**Issue by Daveiano** [drupal-graphql/graphql#694]
I am using the current Drupal GraphQL Module on a Drupal site which has a fully decoupled frontend, both running with https. The Frontend uses react-apollo with the client pointing to the https Drupal graphql endpoint.

My Problem is that the client fetches the data via https, but for example, image URLs are coming with HTTP, not HTTPS, so I am getting a lot of:

``Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS.``

Since the request is correctly done via HTTPS, I am assuming it`s the Drupal GraphQL Module, any feedback on this?

**Comment by pmelab** [comment]
Could you give us an example query where this happens?

**Comment by Daveiano** [comment]
Sure:

```
query artistDetail($path: String!) {
    route(path:$path){
      ... on EntityCanonicalUrl {
        nodeContext {
          ...ArtistsDetail
        }
      }
    }
  }

  fragment ArtistsDetail on NodeArtist {
    title
    fieldLinkedArtist {
      targetId
    }
    body {
      value
    }
    fieldImageOfArtist {
      image:derivative(style: ARTIST_DETAIL) {
        url
      }
    }
  }
```

On `fieldImageOfArtist` I am getting a http link to the image:derivative file.

**Comment by fubhy** [comment]
@Daveiano You do not need to go through the nodeContext in that query. The route itself is already capable of directly returning the route entity (the ArtistDetails node in this case). I suspect, that the issue is caused by our sub requests which would make sense in this case because the nodeContext actually triggers an http kernel internal subrequest. Can you try to just try to use the "entity" field within "EntityCanonicalUrl"?

We still need to fix this bug (use the right protocol for subrequests), but you should be able to get it to work this way.

**Comment by fubhy** [comment]
This query should work:

```
query artistDetail($path: String!) {
    route(path:$path){
      ... on EntityCanonicalUrl {
        entity {
          ...ArtistsDetail
        }
      }
    }
  }

  fragment ArtistsDetail on NodeArtist {
    title
    fieldLinkedArtist {
      targetId
    }
    body {
      value
    }
    fieldImageOfArtist {
      image:derivative(style: ARTIST_DETAIL) {
        url
      }
    }
  }
```

**Comment by Daveiano** [comment]
I am getting the same image url with HTTP with this query. Is there something in Drupal I am missing, some config?

**Comment by pavlosdan** [comment]
Could it be a server configuration issue? We are fully decoupled as well and we didn't do anything special for https in Drupal and we are using nodeContext as well.

**Comment by Daveiano** [comment]
About what kind of server configuration you are thinking? Some hints?

**Comment by pavlosdan** [comment]
I was thinking about rewriting http to https but somehow I don't see why that would be the issue to be honest. 

I just did a test with the derivative field on our QA environment and I couldn't replicate the issue.

For lack of a better feedback to give: https://www.drupal.org/https-information#how-to-enable 
it has links to the server configurations. 

What we are doing in our NGINX config is redirect any requests to http to https.

**Comment by Daveiano** [comment]
Our Drupal lives in a docker container with a port based mapping and also behind a proxy. After a lot of try and error I found a solutions which works for my situation: I added the `file_public_base_url` inside settings.php:

`$settings['file_public_base_url'] = 'https://' . $_SERVER[SERVER_NAME]  . '/sites/default/files';`

This way all assets are provided by Drupal & GraphQL with https.

**Comment by acha5066** [comment]
I think this is not a problem with sub requests but an issue with certain types of server configurations (notably with docker). My query has no sub requests AFAIK but I'm still getting the non secure urls. I have a very similar setup to @Daveiano with Drupal in a docker container but sitting behind a reverse proxy (traefik) which redirects http to https. However, because the url is generated inside the container this redirection never occurs so it just generates the http url. See `PublicStream::baseUrl` at https://git.drupalcode.org/project/drupal/-/blob/8.8.x/core/lib/Drupal/Core/StreamWrapper/PublicStream.php

I had the same fix as above, with one small variation which should be slightly more robust if you have multisite or something running.

```
$settings['file_public_base_url'] = 'https://' . $_SERVER[SERVER_NAME] . '/' . \Drupal\Core\StreamWrapper\PublicStream::basePath();
```

**Comment by pperle** [comment]
@acha5066 Thanks a lot! At least with Drupal 9 one should put `SERVER_NAME` in quotes.

```php
$settings['file_public_base_url'] = 'https://' . $_SERVER['SERVER_NAME'] . '/' . \Drupal\Core\StreamWrapper\PublicStream::basePath();
```
