### ISSUE TITLE
Add partial caching of query results (like dynamic page cache).

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#70]

**Comment by fubhy** [comment]
I'd like to tackle this as the "next big" issue (work on other stuff can of course continue but I'd like to make this our next big goal). Let's set up call with the people who've been involved in this so far? @pmelab @ohthehugemanatee? Maybe we can get some input from @wimleers and @dawehner too on this one?

**Comment by fubhy** [comment]
Would next week work for you? Tuesday evening maybe? Or Wednesday (any time works for me on Wednesday)

**Comment by wimleers** [comment]
Let me know if you want my input :)

**Comment by fubhy** [comment]
@wimleers I would love to have a meeting with you to show you the current status quo of the caching setup and get some feedback and talk about possible next steps. Do you have time for that in the upcoming days? Early next week maybe?

**Comment by dawehner** [comment]
Instead of hitting the cache system with a lot of cache requests, I'm wondering whether it could be an opt in thing, aka. the developer specifies somehow explicitily on which levels partial caching makes sense. This could then drastically remove the amount of cache requests one have to deal with, while being quite efficient, as the developer can know which levels are really worth caching.

On top of that, it could be quite beneficial to have some kind of automatic performance measurement for each part the result.

**Comment by sebas5384** [comment]
Is this issue stale?

**Comment by duartegarin** [comment]
Very interested in this.
Is there any progress on this front?

**Comment by fubhy** [comment]
We are adding this in the next release. Not earlier. Sorry. We are currently working on SDL and Context Definiton based schemas which is going to enable this across the board. And we are totally excited about it.
