### ISSUE TITLE
Version 3 and 4

### ISSUE THREAD

**Issue by bartlangelaan** [drupal-graphql/graphql#706]
I noticed that there are two active branches: 3.x and 4.x.

What are the general changes / improvements / goals of version 4? 
Is there a list of issues that need to be fixed before it can become the default branch?

There are [so many changes](https://github.com/drupal-graphql/graphql/compare/8.x-4.x) that it's hard to see what the improvements over the previous version are.

**Comment by pmelab** [comment]
Yes, we are simultaneously working on a 4.x branch. This version turns the concept upside down. Instead of providing a fixed schema out of the box, it will be possible to feed it a [custom schema definition](https://www.prisma.io/blog/graphql-sdl-schema-definition-language-6755bcb9ce51) and assemble simple I/O plugins (currently called "Data producers") to fill it with functionality. But its still heavily worked on.

Eventually, we plan to provide the same out-of-the-box schema from version 3 also in version 4 to get the best of both worlds. But until there is a seamless upgrade path, v3 will remain fully maintained.

**Comment by pmelab** [comment]
The [SchemaTest](https://github.com/drupal-graphql/graphql/blob/8.x-4.x/src/Plugin/GraphQL/Schema/SdlSchemaTest.php) plugin is currently the best description of the concept if you are interested in it.

**Comment by flesheater** [comment]
Oh, that's perfect bit of information.
Thank you!
