### ISSUE TITLE
4.x: EntityBuffer is missing entity view access check

### ISSUE THREAD

**Issue by klausi** [drupal-graphql/graphql#741]
Hi,

I just looked at https://github.com/drupal-graphql/graphql/blob/8.x-4.x/src/GraphQL/Buffers/EntityBuffer.php you could not see where entity access checks are performed. Maybe that is done somewhere else? Not really familiar with the 4.x code base, can you point me to the place where that is done?

**Comment by joaogarin** [comment]
Hey just adding a bit more info on a quick test I just did, with a simple entity_load property (directly just returning a node) similar to what is in the test schema, doesn't look like its being checked for access : 

``` 
$registry->addFieldResolver('Query', 'node',
      $builder->produce('entity_load', [
        'mapping' => [
          'entity_type' => $builder->fromValue('node'),
          'entity_id' => $builder->fromArgument('id'),
        ],
      ])
    );
```

https://github.com/drupal-graphql/graphql/blob/8.x-4.x/src/Plugin/GraphQL/Schema/SdlSchemaTest.php#L65

**Comment by fubhy** [comment]
Sorry for the late reply. As discussed previously, the access check should be added to the EntityLoad and EntityLoadByUuid data producers instead. I think the buffer should not have access checks because it might also be used for loading intermediary entities and a lot of entity types don't properly implement the full entity access API (that's a whole different problem tbh). The access check should be enabled by default with the option of disabling it with an optional parameter in the data producer.

**Comment by wimleers** [comment]
> and a lot of entity types don't properly implement the full entity access API

… really? 😨 Can you give examples?

>  access check should be added to the EntityLoad and EntityLoadByUuid data producers instead

Does this mean the 4.x branch of the GraphQL is currently insecure?

**Comment by fubhy** [comment]
> … really? fearful Can you give examples?

Loads of contrib (maybe also core?! (not sure)) config entity types just generally return access denied instead of implementing any permissions, etc. That's convenient but then again makes it impossible to generically abstract in cases like ours for instance.

> Does this mean the 4.x branch of the GraphQL is currently insecure?

No, 4.x is a module for developers (at least so far). You build your schema custom from scratch and there are of course data producers (entity_access) that allow you to compose this yourself.

**Comment by fubhy** [comment]
The comment I made before was a suggestion for sane defaults without having to compose it with entity_access yourself (save some lines of code in user space implementations).
