### ISSUE TITLE
Allow scheme plugin to override error formatter and error handler.

### ISSUE THREAD

**Issue by rthideaway** [drupal-graphql/graphql#755]
At the moment there is no option to override error formatter and error handler, so the default ones are used:
https://webonyx.github.io/graphql-php/error-handling/#custom-error-handling-and-formatting

But there might be a need to adjust both error formatter and error handler. For example when throwing default UserError one might need to remove some properties like locations or path, or even add new ones. The same goes for error handler when you might need to handle specific errors in different way than the default.

This applies to the use case when the developer does not want to create validation errors as part of the schema, but want to leverage the webonyx error handling -> https://github.com/webonyx/graphql-php/blob/master/docs/error-handling.md

This PR allows to set custom error formatter and error handler:
https://github.com/drupal-graphql/graphql/pull/754

**Comment by pmelab** [comment]
Closing, since the PR has been merged. Thanks!

**Comment by TheCelavi** [comment]
I believe that this issue should be reopened, this does not work. PR is accepted but there are no tests which confirms desired behaviour. When applied, doesn't work.

Implementation is broken, methods `getErrorFormatter()` and `getErrorHandler()` are unused so any kind of "customisation" is futile. 

I am not expert in Drupal, but what is seams is that in method `configuration()` of class `Drupal\graphql\Entity\Server`: https://github.com/drupal-graphql/graphql/blob/eb467d63f552f68529bb6476a0c1efa18d34f28f/src/Entity/Server.php#L232 

two lines are missing:

```php
  $server->setErrorFormatter($this->getErrorFormatter());
  $server->setErrorsHandler($this->getErrorHandler());
```

I don't have unit tests to share which will confirm that this works. In subclass of this class we did override `configuration()` method to add those two lines and can confirm that it works.

I am not Drupal contributor, nor do I intend to be - if you believe my comment is valid, feel free to implement fix. Otherwise, feel free to ignore it. 

Either way - thank you for your time and thanks for plugin :)
