### ISSUE TITLE
Best practices around deploying a decoupled frontend with Drupal schema changes

### ISSUE THREAD

**Issue by ElijahLynn** [drupal-graphql/graphql#777]
Are there any known best practices around deploying schema changes in Drupal along with GraphQL that don't break the consumer(s)? I know GraphQL doesn't have versioning per say. So how do we handle a schema change that needs to be deployed in Drupal, and won't break the frontend?

**Comment by ElijahLynn** [comment]
I see mention of the 4.x branch here https://www.amazeelabs.com/en/blog/state-graphql-drupal:
> Some of you already noticed that there is a 4.x branch of the GraphQL module lingering, and there have been a lot of questions what this is about. This new version has been developed in parallel over the last year (mainly sponsored by our friendly neighbourhood car manufacturer Daimler) with an emphasis on GraphQL schema definitions.

> Instead of just exposing everything Drupal has to offer, it allows us to craft a tailored schema that becomes the single source of truth for all information, operations, and interactions that happen within the system. This contract is not imposed by Drupal, but by the business needs that have to be met.

Is the solution around this using the GraphQL Schema Definitions? I see how this could help a little but not solve it completely, e.g. renaming a field in Drupal schema. 

cc @pmelab

**Comment by ElijahLynn** [comment]
After thinking and reading some more, my current understanding it would seem that GraphQL Schema Definitions would need to take care of how to handle this renamed field and be updated accordingly along with the code changes that change the schema. It seems like there would need to be a decent amount of tests written around expected return values etc. 

Is that about right?

**Comment by ElijahLynn** [comment]
Would love some links to these discussions around ~this new feature~ GraphQL Schema Definitions in the 4.x branch.

**Comment by pmelab** [comment]
Instead of renaming a field, you would just register it under the new name and mark the old one as `@deprecated`, and remove it when you know that clients are updated. But that's not solved by the schema definition directly.

V3 of the GraphQL module infers the schema from Drupal's internal structures, which is its power and its curse. You get everything for free, but Drupal might also change the schema under your feet. We even had a case where a Drupal core update changed the type of an internal field property which caused a breaking schema change. You can handle it the same way, by deprecating/altering fields to maintain compatibility. But it's hard to do that in the long run because alterations will add up.
V4 puts the schema into developers hands, which makes it a little harder to get started, but a lot more stable and maintainable.

**Comment by ElijahLynn** [comment]
Thank you for this input, so the approach really here is a change in development style and being thoughtful about schema changes and marking things as `@deprecated` etc, which I assume you just mean in a docblock. 

Can you elaborate a bit more about V4? My understanding is that we create a type or middle-schema where we do the mapping and have control over that, we would then use that in conjunction with `@deprecated`. It would create more schema maintenance while providing the benefit of not breaking consumer applications.
