### ISSUE TITLE
Subrequest to a views page throws an exception

### ISSUE THREAD

**Issue by blazeyo** [drupal-graphql/graphql#807]
Doing a subrequest to a view page's route results in a fatal error because of [this line](https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/GraphQL/Buffers/SubRequestBuffer.php#L107). View pages require the format to be set to html and therefore [this condition](https://github.com/drupal/drupal/blob/8.8.x/core/lib/Drupal/Core/Routing/RequestFormatRouteFilter.php#L48) isn't matched for them. That results in [an exception](https://github.com/drupal/drupal/blob/8.8.x/core/lib/Drupal/Core/Routing/RequestFormatRouteFilter.php#L65)

**Comment by blazeyo** [comment]
The line looks like a leftover. #808 removes it.

**Comment by Breuls** [comment]
@blazeyo The line isn't a leftover. I introduced it in #705.

I also wrote a lengthy explanation because I wasn't sure it would be a durable fix for the problem that it fixes (it felt like a hack to me, but I couldn't think of anything better), so I can understand it being removed some time later. Removing it might however bring back the original bug. ;)

**Comment by blazeyo** [comment]
@Breuls Thanks for pointing that out. In this case, it might make sense to re-open the original issue and look for another solution.
