### ISSUE TITLE
Move the APQ module into drupal-graphql organization

### ISSUE THREAD

**Issue by sebas5384** [drupal-graphql/graphql#848]
I talked with @lucasconstantino about moving the [APQ](https://github.com/lucasconstantino/drupal-graphql-apq) module into the https://github.com/drupal-graphql organization and it makes sense for us, so others can make progress on releasing a package and be available at drupal.org

This make sense? if so, then let's do it!

**Comment by lucasconstantino** [comment]
First thing would probably be to transfer ownership to drupal-graphql organization. Once you guys agree with this approach, I'll make the first migration.

After moving the repository, the second step would probably be to add alerts on on-going development for new version compatibility, and maybe some work-in-progress warnings on the README, at least until we refactor some of the documentation (and code, if feasible) to match that of drupal-graphql's patterns.

If possible, I would also like to maintain editing capabilities on the repo.

**Comment by lucasconstantino** [comment]
Another thing I'm not really comfortable with is the fact that drupal-graphql organization currently has only one member - @joaogarin. This is never desirable for open-source. I would strongly recommend more people are added to the org. Would be great to have this resolved before transferring ownership, though I'm open for discussions on this.

**Comment by joaogarin** [comment]
Where do you see this? At least @klausi and @justinlevi I think are also members. maybe because they don't set it publicly in their profiles you can not see it? but overall..I guess I agree ;P Not using APQ module though so can't talk much about this issue. but the more complete we make the GraphQL ecosystem overall the better 👏

**Comment by fubhy** [comment]
I am all for adding more people to the organization / welcoming more contributors. Currently there are 5 people on the organization already though. Not sure why you can't see them. Probably because of what @joaogarin said. 

Regarding adding the module to the organization: Sure, we can do that for 3.x - For the 4.x branch and onwards, since we are going to have a plugin system for things like that. We can add all that to the core module without it getting in the way. Same goes for all the other pieces that were distributed across several separate modules in 3.x like graphql_views, graphql_metatag, etc. - I want to make all that part of the main module because we can just put that into separate data producer plugins in this case.

Hence, there's going to be much less need for extra modules.

**Comment by lucasconstantino** [comment]
@joaogarin @fubhy indeed I can't see the organisation members, but I'm fine if you guys say there is more people on it ;)

So, how should we proceed with this? Can I simply transfer the repository to `drupal-graphql` and we go from there?

**Comment by fubhy** [comment]
I actually can't add more without buying an organization subscription from Facebook. @pmelab can you maybe check with AmazeeLabs if they want to sponsor that? ;-)

If not, we could check if we can get an open source sponsorship from Github directly for instance...

**Comment by fubhy** [comment]
I tried adding you @lucasconstantino despite the limit on the seats. It seems to have worked? Can ytou check if you got an invite in your mailbox? All these modules (APQ, Metatags integration, etc.) should get a note that they are solely for the 3.x branch imho and we should look into merging their functionality into the core module. @chindris is already working on a plugin driven solution for persisted queries. The APQ integration would just be an implementation of such a plugin at that point for instance. The metatags / search api integration modules would just expose DataProducer plugins with the "provider" property on the plugin annotation set to the underlying module.

**Comment by lucasconstantino** [comment]
@fubhy I've accepted the invitation to the organization, and I have tried moving the repository there. I don't currently have permission to create repositories there, though.

**Comment by fubhy** [comment]
@lucasconstantino Alright, I updated the permissions. You should be able to create repositories now.

**Comment by lucasconstantino** [comment]
@fubhy so, here are some updates:

1. I've moved the repository;
2. I've removed myself from the @drupal-graphql org;

Also, I would ask you to me and add @sebas5384 as contributors to this repository alone - unless there is intend for a more close relationship, then a simple suggest to add @sebas5384 as a member of the org.

**Comment by lucasconstantino** [comment]
@fubhy ps.: this was the list of "private" contributors... I would recommend you share this with them, it's probably better to have it publicly visible, if they don't mind ;)

![joxi_screenshot_1563890942015](https://user-images.githubusercontent.com/2688512/61719737-d3d2e400-ad3b-11e9-8533-6afa5c042ae3.png)

**Comment by fubhy** [comment]
You could've stayed in the organization as far as I am concerned ;-). I'll add you and @sebas5384 to the repo too anyways.
