### ISSUE TITLE
4.x: Early rendering issue when querying for all menus

### ISSUE THREAD

**Issue by justin-longbottom** [drupal-graphql/graphql#887]
The example module shows how to get all articles, as opposed to knowing specific IDs. I am trying to do the same thing for menus, but it fails when I add the url to the query.

`The controller result claims to be providing relevant cache metadata, but leaked metadata was detected. Please ensure you are not rendering content too early`

```
{
menus {
    items {
      name
      title
      icon
      url {
        path
      }
    }
  }
}
```
When I remove `url` from my query, it works again.

It looks like `$link->getUrlObject();` in the `menu_link_url` producer is the culprit. Or at least anytime that gets called, I get the error.

MenuConnection Wrapper
```
  public function items() {
    $result = $this->query->execute();
    if (empty($result)) {
      return [];
    }

    $buffer = \Drupal::service('graphql.buffer.entity');
    $callback = $buffer->add($this->query->getEntityTypeId(), array_values($result));
    return new Deferred(function () use ($callback) {
      return $callback();
    });
  }
```

QueryMenus data producer
```
  public function resolve(RefinableCacheableDependencyInterface $metadata) {

    $storage = $this->entityManager->getStorage('menu');
    $type = $storage->getEntityType();
    $query = $storage->getQuery()
      ->currentRevision()
      ->accessCheck();

    $metadata->addCacheTags($type->getListCacheTags());
    $metadata->addCacheContexts($type->getListCacheContexts());

    return new MenuConnection($query);
  }
```

**Comment by fubhy** [comment]
Is it really the url object or the stringification of the url object further down the line?

In any case, the fix is adding a RenderContext around it like e.g. here: https://github.com/drupal-graphql/graphql/blob/bd84deff16a2d9dc25f9891e059d44290f286760/src/Plugin/GraphQL/DataProducer/Entity/EntityRendered.php#L108-L118

Would you mind submitting a pull request for the problematic DataProducer? 

If the problem is not in the menu_link_url data producer it might be here: https://github.com/drupal-graphql/graphql/blob/8.x-4.x/src/Plugin/GraphQL/DataProducer/Routing/Url/UrlPath.php

**Comment by fubhy** [comment]
@justin-longbottom Hey there. Just to check: Are you going to submit this resolution (assuming it works?!) as a pull request? :-)

**Comment by justin-longbottom** [comment]
At some point I had to rebuild my local and the issue simply went away. Still not sure why. Must have been something else I was tinkering with. I will close this issue for now. Thanks for being so responsive.
