### ISSUE TITLE
Empty response with 200 response code

### ISSUE THREAD

**Issue by ElijahLynn** [drupal-graphql/graphql#904]
We are getting a 200 response code with a zero byte response body. The issue appears to be related to the amount of nodes, which is a bit over 700 published nodes we are querying for. 

If I make the query multiple times it eventually succeeds and then does from then on, until I cache:rebuild, then the error state is reset again. 

If I unpublish 200 nodes then the issue does not happen. I don't _think_ this is graphql module because locally I don't get the issue but only get it on our CI server, so it may be the CI stack. Mainly putting this here for rubber ducking purposes.

**Comment by ElijahLynn** [comment]
K, figured it out by rubber ducking in a text scratchpad:

It turned out to be memory exhaustion (local `memory_limi` was 1G, CI was 256M). And the PHP `error_log` wasn't set so the error never made it anywhere except to the Apache request log. Combined with a `200 Success` response code, it made for the perfect combo of confusion. 

I think the memory exhaustion with a 200 error is a bug but not sure if it is GraphQL or Drupal Core. I am going to leave this open so we can rule out GraphQL returning a 200 with a memory exhaustion.

**Comment by fubhy** [comment]
If you are getting no response body whatsoever, then this is not within the graphql module. If the response contains a "errors" property, then it contains errors that were caught by graphql. In that case, the response code would be 200 indeed because it's a "valid" graphql response (albeit with errors that the client then needs to handle). You can check whether it's a graphql returned response by setting an xdebug breakpoint around here: https://github.com/drupal-graphql/graphql/blob/8.x-4.x/src/Controller/RequestController.php#L74

If it get's through to that point, the request was finished with graphql. If it does not (meaning an uncaught exception occurred) then it means that Drupal is returning the 200. Another possible scenario is that neither of the two actually handles it and instead the php interpreter itself (e.g. php-fpm) is returning it. I am currently not sure at what level a engine error (like memory limit) is handled or whether it's even catch-able in the php code itself?

Side-node: Especially with persisted queries (using GET requests for these queries) it might be required to override that response code if you want to prevent caching of these response. But that's another story.

**Comment by ElijahLynn** [comment]
Thanks @fubhy the breakpoint line is a great lead! I'll test that soon. We can close this for now, and I'll post back status when I test and if relevant then I'll reopen. We are using Apache's mod_php fwiw.
