### ISSUE TITLE
entity_load type menu return null

### ISSUE THREAD

**Issue by yvmarques** [drupal-graphql/graphql#927]
Hello,

I have a query that returns menu items for a given name (menuByName). it uses the producer `entity_load`.

I noticed that since the access check was implemented, this producer returns NULL.

I dug a bit to understand why and I found that I have a module `access_unpublished` that check if the current user has a right to see the unpublished content. This module has a hook that works on all the entities.

By default `access_unpublished` return `AccessResult::neutral()` when it doesn't pass, it's hook `_entity_access`.

Later in the code, for the entity `menu` if there is a `AccessResult::neutral()` Drupal searches for `getAdminPermission()` and because the anonymous user doesn't have those rights, then the access is forbidden and the producer returns NULL.

**Comment by ndrake0027** [comment]
I had a similar problem. In my menu query resolver I added setting `access` to `false`. All the menu items still use the the access checker before they are loaded: 
```
private function createMeagMenuQuery(ResolverBuilder $builder, ResolverRegistryInterface $registry) {
    $registry->addFieldResolver('Query', 'menu',
      $builder->produce('entity_load')
        ->map('type', $builder->fromValue('menu'))
        ->map('id', $builder->fromArgument('name'))
        ->map('access', $builder->fromValue(FALSE))
    );
  }
```

**Comment by yvmarques** [comment]
@fubhy This was closed without explanation, just to be sure does it mean that for this to work, we need set `access` to `FALSE`  as @ndrake0027 said ?

Thanks

**Comment by fubhy** [comment]
As you already correctly figured out by yourself, the problem lies in the access check result being `neutral`. Drupal, in this case, goes with assuming `access denied` by default for security reasons. Access is only granted if access is explicitly set to `allowed`. Hence, this is not a problem with the implementation of the `entity_load` data producer. If you want, you can set `access` to FALSE which will disable all access checks entirely. Be warned though that, well, it disables all access checks for this instance of `entity_load`. The 100% right approach would be to properly return `allowed` in the access check itself, so fix whatever returns `neutral` or `forbidden` to instead return `allowed`.
